### ISSUE TITLE
i18n for enums

### ISSUE THREAD

**Issue by alexsuter** [abhi1693/yii2-enum#2]
Hi

I have a feature request. What about i18n? Translation for every Enum-Value. I would like to call

``` php
echo $myEnumObject->t();
```

I would like to have for every Enum one message file, placed under:

```
messages\[locale]\enum\MyEnum.php
```

The message file looks like:

``` php
use app\..\MyEnum;
return [
        MyEnum::Value1 => 'Translated Value'
];
```

What do you think?

Thank you

**Comment by abhi1693** [comment]
That is a good suggestion. But currently I'm busy with some other project, send me a PR.
